"""Supporting-document persistence: the insert, the scoped read, the OD#2 replace (Story 4.1).

Implements: AC1 (`insert_supporting_document` persists the row the upload command composed —
`storage_name` server-generated, `original_filename` verbatim DATA), AC5
(`get_supporting_document`, the scoped read the streaming GET locates through — the scope a SQL
predicate, never a post-filter, AD-10/NFR-04), Open Decision #2 (`update_supporting_document`,
the attach-or-replace while PENDING; migration `0013`'s grant carries `UPDATE` for exactly this).
FR-13, NFR-05, AD-15. SM-6.

One repository module per table (the rule Story 2.9 fixed) — these functions are NOT added to
`repositories/leave_request.py`, whose surface `test_leave_request_submit.py` pins BY NAME.

--- The mutation surface: an INSERT and ONE narrow UPDATE; no delete ---

`update_supporting_document` rewrites the three content columns in place (new `storage_name` /
`original_filename` / `content_type`) — OD#2's replace, guarded by the SERVICE (PENDING-only;
the service resolved the existing row under the request locate first). There is no
`delete_supporting_document`: no requirement deletes a document, the grant withholds `DELETE`,
and tests clean up through the `owner_engine` fixture (the Story 2.9 precedent). The
`UNIQUE (leave_request_id)` is the AD-5 BACKSTOP — the service's insert-or-update decision is
the gate, so the constraint never surfaces as a raw 500.

--- Why the scoped getter joins `leave_request` → `employee` ---

A document belongs to a request, and a request to an Employee; the scope helper
(`employee_scope_predicate`) predicates over the `Employee` table, so the getter walks the two
FKs to reach it. Belt-and-braces BY DESIGN: the service has already located the request under
the caller's scope, and this getter re-applies the same predicate in ITS OWN SQL — a second,
independent enforcement of AD-10 on the read that actually serves bytes. It takes the parameter
literally named `actor` (`test_scoped_getters.py`), and is NOT exemptible: a document is
Employee-derived data if anything is.
"""

import uuid

from sqlalchemy import Row, select, update
from sqlalchemy.orm import Session

from app.repositories.models import Employee, LeaveRequest, SupportingDocument
from app.repositories.scoping import Scope, employee_scope_predicate

# Plain COLUMNS, never the ORM entity (the `leave_request._READ_COLUMNS` idiom): a `Row` of
# columns is already detached, so nothing lazy-loads or expires once the read session closes.
# Exactly what the two consumers need — the GET streams by `storage_name`/`content_type`/
# `original_filename`; the POST response projects `id`/`original_filename`/`content_type`.
_READ_COLUMNS = (
    SupportingDocument.id,
    SupportingDocument.leave_request_id,
    SupportingDocument.storage_name,
    SupportingDocument.original_filename,
    SupportingDocument.content_type,
)


def insert_supporting_document(
    session: Session,
    *,
    leave_request_id: uuid.UUID,
    storage_name: uuid.UUID,
    original_filename: str,
    content_type: str,
) -> SupportingDocument:
    """Insert a supporting-document row and return it, with its server-default id assigned.

    `flush` assigns the `uuidv7()` `id` so the route can project the 201 response; it does NOT
    commit — the service owns the one transaction (AD-3), and OD#4's ordering (row flush → file
    write → commit) depends on exactly that. `storage_name` is SERVER-generated by the service
    (`uuid.uuid4()`), never derived from anything the client sent; `original_filename` is
    persisted VERBATIM as data (NFR-05) — even a traversal-shaped name is just a string here.

    A write, governed by the command's transaction rather than the scope contract, so it is not
    a scoped-getter candidate — mirroring `insert_leave_request`. The caller has already decided
    insert-vs-update (OD#2): reaching this with an existing row would fire the UNIQUE backstop,
    which is the caller's defect, not this function's gate.
    """
    document = SupportingDocument(
        leave_request_id=leave_request_id,
        storage_name=storage_name,
        original_filename=original_filename,
        content_type=content_type,
    )
    session.add(document)
    session.flush()
    return document


def get_supporting_document(
    session: Session,
    actor: Employee,
    *,
    leave_request_id: uuid.UUID,
    scope: Scope,
) -> Row | None:  # type: ignore[type-arg]
    """Return the document attached to this request, SCOPED to `actor`, or `None` (AC5).

    Keyed by `leave_request_id` — the UNIQUE constraint makes it at most one row. Joins
    `supporting_document → leave_request → employee` and applies
    `employee_scope_predicate(scope, actor)` IN THE SQL (AD-10, NFR-04): an out-of-scope
    document is never retrieved, and the service turns the `None` — a nonexistent request, an
    out-of-scope one, or a request with no document — into the ONE byte-identical
    `404 RESOURCE_NOT_FOUND` (AC5). Belt-and-braces with the service's own request locate, by
    design: the read that serves bytes enforces the scope itself, in its own query.

    A `get_` getter taking a `session`, so `test_scoped_getters.py` requires the `actor`,
    which it takes. Returns the `_READ_COLUMNS` projection, not the ORM entity.
    """
    return session.execute(
        select(*_READ_COLUMNS)
        .join(LeaveRequest, SupportingDocument.leave_request_id == LeaveRequest.id)
        .join(Employee, LeaveRequest.employee_id == Employee.id)
        .where(
            SupportingDocument.leave_request_id == leave_request_id,
            employee_scope_predicate(scope, actor),
        )
    ).first()


def update_supporting_document(
    session: Session,
    *,
    leave_request_id: uuid.UUID,
    storage_name: uuid.UUID,
    original_filename: str,
    content_type: str,
) -> None:
    """Replace the document attached to this request IN PLACE — OD#2's replace path.

    Rewrites the three content columns on the ONE row `UNIQUE (leave_request_id)` guarantees;
    the row's `id` is stable across replacements. GUARDED BY THE SERVICE, not here: the service
    has already located the request under `Scope.SELF`, confirmed it is still `PENDING`
    (a decided request's evidence is frozen — OD#2), and read the existing row whose old
    `storage_name` it will best-effort unlink after commit. Migration `0013`'s grant carries
    `UPDATE` for exactly this call; `DELETE` stays withheld.

    `synchronize_session=False`: the caller does not reuse a stale ORM object's columns after
    the UPDATE — it already holds the new values it just passed. `flush` is implicit in
    `execute`; the SERVICE owns the `commit` (AD-3).
    """
    session.execute(
        update(SupportingDocument)
        .where(SupportingDocument.leave_request_id == leave_request_id)
        .values(
            storage_name=storage_name,
            original_filename=original_filename,
            content_type=content_type,
        )
        .execution_options(synchronize_session=False)
    )
    session.flush()
