"""The ORM models and the migration history agree — `alembic check` is green.

Implements the enforcement the model and migration docstrings PROMISE but nothing else
delivers: `repositories/models.py` and each migration claim they stay "byte-for-byte
faithful" to one another "because `alembic check` emits an empty diff only while they
agree". That guarantee is only real if something runs `alembic check`. This test is that
something — `pytest` is the build (F-14), so a model edited without a matching migration
(or a migration without a matching model) fails here rather than surfacing at runtime as
an INSERT/SELECT against a column that exists in one and not the other.

Runs against real PostgreSQL: `alembic check` compares `Base.metadata` to the *live*
database, so it needs the database migrated to head — exactly the state AC1's setup
sequence leaves it in. Depends on `db_connection` only to inherit its skip-when-DB-absent
behaviour; the check opens its own connection through `env.py`.
"""

from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import Connection

BACKEND_ROOT = Path(__file__).resolve().parents[2]


def test_models_and_migrations_agree(
    db_connection: Connection, monkeypatch: pytest.MonkeyPatch
) -> None:
    """`alembic check` finds no diff between the models and the migrated schema.

    The chdir makes `alembic.ini`'s relative `script_location = alembic` resolve
    independently of where `pytest` was invoked from — the same pattern
    `test_architecture.py` uses for `lint_imports`.
    """
    monkeypatch.chdir(BACKEND_ROOT)
    config = Config(str(BACKEND_ROOT / "alembic.ini"))

    try:
        command.check(config)
    except AutogenerateDiffsDetected as diffs:
        pytest.fail(
            "The ORM models and the migrations disagree — `alembic check` found a diff:\n"
            f"{diffs}\n"
            "Change one, change both: edit app/repositories/models.py and add a matching "
            "migration in alembic/versions/ in the same commit."
        )
